import sys, os
sys.path.append(os.path.abspath('..'))
from common import *

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

#htmlhelp_basename = 'udigdoc'
