/**
 * <copyright>
 * </copyright>
 *
 * $Id: RenderItemProviderAdapterFactory.java 21423 2006-09-14 19:17:05Z jeichar $
 */
package net.refractions.udig.project.internal.render.provider;

import java.util.ArrayList;
import java.util.Collection;

import net.refractions.udig.project.internal.render.util.RenderAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The
 * adapters generated by this factory convert EMF adapter notifications into calls to
 * {@link #fireNotifyChanged fireNotifyChanged}. The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 *
 * @generated
 */
public class RenderItemProviderAdapterFactory extends RenderAdapterFactory
        implements
            ComposeableAdapterFactory,
            IChangeNotifier {
    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public static final String copyright = "uDig - User Friendly Desktop Internet GIS client http://udig.refractions.net (C) 2004, Refractions Research Inc. This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; version 2.1 of the License. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details."; //$NON-NLS-1$

    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by
     * {@link #isFactoryForType isFactoryForType}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection supportedTypes = new ArrayList();

    /**
     * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public RenderItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link net.refractions.udig.project.internal.render.RenderManager} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected RenderManagerItemProvider renderManagerItemProvider;

    /**
     * This creates an adapter for a
     * {@link net.refractions.udig.project.internal.render.RenderManager}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public Adapter createRenderManagerAdapter() {
        if (renderManagerItemProvider == null) {
            renderManagerItemProvider = new RenderManagerItemProvider(this);
        }

        return renderManagerItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link net.refractions.udig.project.internal.render.Style} instances. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    protected StyleItemProvider styleItemProvider;

    /**
     * This creates an adapter for a {@link net.refractions.udig.project.internal.render.Style}.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public Adapter createStyleAdapter() {
        if (styleItemProvider == null) {
            styleItemProvider = new StyleItemProvider(this);
        }

        return styleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link net.refractions.udig.project.internal.render.ViewportModel} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ViewportModelItemProvider viewportModelItemProvider;

    /**
     * This creates an adapter for a
     * {@link net.refractions.udig.project.internal.render.ViewportModel}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public Adapter createViewportModelAdapter() {
        if (viewportModelItemProvider == null) {
            viewportModelItemProvider = new ViewportModelItemProvider(this);
        }

        return viewportModelItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link net.refractions.udig.project.internal.render.RenderExecutor} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected RenderExecutorItemProvider renderExecutorItemProvider;

    /**
     * This creates an adapter for a
     * {@link net.refractions.udig.project.internal.render.RenderExecutor}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public Adapter createRenderExecutorAdapter() {
        if (renderExecutorItemProvider == null) {
            renderExecutorItemProvider = new RenderExecutorItemProvider(this);
        }

        return renderExecutorItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    public void setParentAdapterFactory( ComposedAdapterFactory parentAdapterFactory ) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public boolean isFactoryForType( Object type ) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public Adapter adapt( Notifier notifier, Object type ) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public Object adapt( Object object, Object type ) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class) || (((Class) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public void addListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public void removeListener( INotifyChangedListener notifyChangedListener ) {
        changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public void fireNotifyChanged( Notification notification ) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

}
