<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="element"
    nsURI="http:///net/refractions/udig/project/element.ecore" nsPrefix="net.refractions.udig.project.element">
  <eClassifiers xsi:type="ecore:EClass" name="ProjectElementAdapter" eSuperTypes="internal.ecore#//ProjectElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backingObject" eType="#//IGenericProjectElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IGenericProjectElement" instanceClassName="net.refractions.udig.project.element.IGenericProjectElement"/>
</ecore:EPackage>
